#! /usr/bin/env bash
## Snakefile
####################
import pandas as pd
import numpy as np

workdir: workflow.basedir + "/../../analysis/snapATAC/"


def get_rank(tissue): 
  f = pd.read_table(tissue+"/"+tissue+".pooled.barcode.cluster.stage.rep.txt")
  return np.max(f['cluster'])

#tissues=["DH","FC","HT","LM"]
tissues=["DH"]
#age_rep=["03_rep1","10_rep1","18_rep1","03_rep2","10_rep2","18_rep2"]
AGES = ["03","10","18"]
REPS = ["rep1","rep2"]
ranks = {tissue:get_rank(tissue) for tissue in tissues}

print(ranks)

localrules: require_files

rule require_files: 
  input:
    expand("{tissue}/bigWig.cluster/{tissue}.bw.xml",tissue=tissues),
    expand("{tissue}/bigWig.cluster_age/{tissue}.bw.xml",tissue=tissues),
    expand("{tissue}/{tissue}.peaks.counts",tissue=tissues)


rule count_reads:
  output:
    "{tissue}/{tissue}.peaks.counts"
  input:
    lambda wildcards: expand(wildcards.tissue+"/bam.cluster_age_rep/"+
    wildcards.tissue+".metacell_{rank}.{age}.{rep}.sorted.bam",
    rank=list(range(1,ranks[wildcards.tissue]+1)),age=AGES,rep=REPS)
  threads: 8
  params:
    pbsName=lambda wildcards: wildcards.tissue
  shell:
    "featureCounts -a ../../data/snATAC/peaks/{wildcards.tissue}.all.pooled_summits.ext1k.saf -o {output} {input} -F SAF -T {threads}"



rule generate_bw_cluster_xml:
  output: 
    "{tissue}/bigWig.{path}/{tissue}.bw.xml"
  input:
    lambda wildcards: expand(wildcards.tissue+"/bigWig."+wildcards.path+"/"+
    wildcards.tissue+".metacell_{rank}.sorted.rpkm.bw",
    rank=list(range(1,ranks[wildcards.tissue]+1)))
  threads: 1
  params:
    pbsName=lambda wildcards: wildcards.tissue
  shell:
    "cd {wildcards.tissue}/bigWig.{wildcards.path}/ &&"
    "python ~/software/github/seq-min-scripts/make_IGV_session.py mm10 "
    "http://renlab.sdsc.edu/yanxiao/mouse_aging/analysis/snapATAC/{wildcards.tissue}/"
    "bigWig.{wildcards.path} {output}"

rule generate_bw_cluster_age_xml:
  output:
    "{tissue}/bigWig.{path}/{tissue}.bw.xml"
  input:
    lambda wildcards: expand(wildcards.tissue+"/bigWig."+wildcards.path+"/"+
    wildcards.tissue+".metacell_{rank}.{age}.sorted.rpkm.bw",
    rank=list(range(1,ranks[wildcards.tissue]+1)),age=AGES)
  threads: 1
  params:
    pbsName=lambda wildcards: wildcards.tissue
  shell:
    "cd {wildcards.tissue}/bigWig.{wildcards.path}/ &&"
    "python ~/software/github/seq-min-scripts/make_IGV_session.py mm10 "
    "http://renlab.sdsc.edu/yanxiao/mouse_aging/analysis/snapATAC/{wildcards.tissue}/"
    "bigWig.{wildcards.path} {output}"


#    "HT/bam.cluster/HT.metacell_1.sorted.bam",
#    "HT/bam.cluster_age/HT.metacell_1.03.sorted.bam",
#    "HT/bigWig.cluster/HT.metacell_1.sorted.rpkm.bw"


rule bamToBigWig:
  output: 
    "{tissue}/bigWig.{path}/{tissue}.metacell_{info}.sorted.rpkm.bw"
  input:
    "{tissue}/bam.{path}/{tissue}.metacell_{info}.sorted.bam"
  threads: 4
  params:
    pbsName=lambda wildcards: wildcards.info
  shell:
    "bamCoverage -bam {input} --outFileFormat bigwig --outFileName {output} "
    "--binSize 25 --normalizeUsing RPKM -p {threads}"


rule sort_bam:
  output: 
    "{tissue}/{bam_dir}/{tissue}.metacell_{ext}.sorted.bam"
  input:
    "{tissue}/{bam_dir}/{tissue}.metacell_{ext}.bam"
  threads: 1
  params:
    pbsName=lambda wildcards: wildcards.tissue+"."+wildcards.ext
  shell:
    "samtools sort -m 4G {input} -o {output};"
    "samtools index {output};"

rule merge_bam_cluster:
  output:
    "{tissue}/bam.cluster/{tissue}.metacell_{cluster}.bam"
  input: 
    expand("{{tissue}}/bam.cluster_age_rep/{{tissue}}.metacell_{{cluster}}.{age}.{rep}.bam",age=AGES,rep=REPS)
  threads: 1
  params:
    pbsName=lambda wildcards: wildcards.tissue+"."+wildcards.cluster
  shell: 
    "samtools merge -f {output} {input}"

rule merge_bam_cluster_age:
  output:
    "{tissue}/bam.cluster_age/{tissue}.metacell_{cluster}.{age}.bam"
  input:
    expand("{{tissue}}/bam.cluster_age_rep/{{tissue}}.metacell_{{cluster}}.{{age}}.{rep}.bam",rep=REPS)
  threads: 1
  params:
    pbsName=lambda wildcards: wildcards.tissue+"."+wildcards.age
  shell:
    "samtools merge -f {output} {input}"

